pipeline {
    agent any
    
    tools {
        maven "maven3"
        jdk "jdk17"
    }
    
    environment {
        AWS_ACCOUNT = '904233099353' // Add your AWS account number here
        ECR_REPO = "${AWS_ACCOUNT}.dkr.ecr.ap-south-1.amazonaws.com/frontend-dev"
        AWS_REGION = 'ap-south-1'
        IMAGE_TAG = "${Release_Version}" // Use BUILD_NUMBER as the tag
        ECS_CLUSTER = 'frontend' // Replace with your ECS cluster name
        ECS_SERVICE = 'frontend-svc' // Replace with your ECS service name
        ECS_TASK_DEF_FAMILY = 'frontend-task' // Replace with your ECS task definition family
        
    }

    stages {
        stage('Deploy to ECS') {
            steps {
                withAWS(credentials: 'Aws-Cred', region: 'ap-south-1') {
                    script {
                        // Update ECS Task Definition with the new image
                        sh """
                        sudo apt-get update && sudo apt-get install -y jq
 
                        # Fetch current task definition and update with new image
                        TASK_DEF=\$(aws ecs describe-task-definition --task-definition ${ECS_TASK_DEF_FAMILY} --region ${AWS_REGION})
                        NEW_TASK_DEF=\$(echo \$TASK_DEF | jq --arg IMAGE "${ECR_REPO}:${IMAGE_TAG}" '.taskDefinition | .containerDefinitions[0].image = \$IMAGE')
                        NEW_REVISION=\$(echo \$NEW_TASK_DEF | jq '. | {family: .family, containerDefinitions: .containerDefinitions, volumes: .volumes, taskRoleArn: .taskRoleArn, executionRoleArn: .executionRoleArn, networkMode: .networkMode, requiresCompatibilities: .requiresCompatibilities, cpu: .cpu, memory: .memory}')
 
                        # Register new task definition revision
                        NEW_TASK_DEF_ARN=\$(aws ecs register-task-definition --region ${AWS_REGION} --cli-input-json "\$NEW_REVISION" | jq -r '.taskDefinition.taskDefinitionArn')
 
                        # Update ECS service to use the new task definition revision
                        aws ecs update-service --region ${AWS_REGION} --cluster ${ECS_CLUSTER} --service ${ECS_SERVICE} --task-definition \$NEW_TASK_DEF_ARN
                        """
                    }
                }
            }
        }  
        
    }
}
